### ISSUE TITLE
Gutenberg LinkIt

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#852]
Improve Gutenbergs link experience by combining it with [Linkit](drupal.org/project/linkit)

There is an open PR: https://www.drupal.org/project/gutenberg/issues/3213528

**Comment by pmelab** [comment]
The goal would be to reuse the existing Gutenberg linking UI, just replace the suggestion callback controller.

**Comment by pmelab** [comment]
Additional requirements that came up:

* make the autocomplete box wider
* ordering of search results by relevance (levenshtein distance?)

**Comment by Leksat** [comment]
Tried to finish the development in [#3213528](https://www.drupal.org/project/gutenberg/issues/3213528) but it isn't that easy.

The [latest patch](https://www.drupal.org/project/gutenberg/issues/3213528#comment-14232809) from the issue does the job. But the complete integration does not seem to be possible because of [Gutenberg's limitations](https://www.drupal.org/project/gutenberg/issues/3213528#comment-14978522).

Yet, we are not affected by the limitations because our `LinkProcessor` does the rest of the job.
